using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DotNetKit.Demo.Data
{
    public sealed class Person
    {
        public long Id { get; private set; }
        public string Name { get; private set; }

        public override string ToString()
        {
            return string.Format("Person(Id = {0}, Name = {1})", Id, Name);
        }

        public Person(long id, string name)
        {
            Id = id;
            Name = name;
        }
    }

    public static class PersonModule
    {
        /// <summary>
        /// List of name automatically generated by http://listofrandomnames.com . Thanks!
        /// </summary>
        static readonly string source =
            @"
AAA
BBC
BBS
";

        static readonly IReadOnlyList<Person> allPersons =
            source.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
            .Select((name, i) => new Person(i + 1L, name))
            .ToArray();

        public static IReadOnlyList<Person> All
        {
            get { return allPersons; }
        }
    }
}
